CREATE TABLE sp_user(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    email VARCHAR(50) NOT NULL,
    password VARCHAR(50) NOT NULL,
    position VARCHAR(50) NOT NULL,
    type INT NOT NULL
);

-- type = 0 -> admin    type = 1 -> user
INSERT INTO sp_user(name, last_name, email, password, position, type)
VALUES ('Admin', 'Admin', 'admin@gmail.com', '123', 'Admin', 0)

CREATE TABLE sp_process(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    description VARCHAR(100),
    published BOOLEAN NOT NULL
);

CREATE TABLE sp_process_step (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    form_structure VARCHAR(100000),
    fields_properties JSON,
    id_process INT NOT NULL,
    CONSTRAINT fk_id_idprocess FOREIGN KEY (id_process)
    REFERENCES sp_process (id)
    ON DELETE CASCADE
);

CREATE TABLE sp_process_step_relation (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_steps_relation JSON,
    id_process INT NOT NULL,
    CONSTRAINT fk_id_idprocess FOREIGN KEY (id_process)
    REFERENCES sp_process (id)
    ON DELETE CASCADE
);